### ISSUE TITLE
Autosave for just .excalidraw files

### ISSUE THREAD

**Issue by Milo123459** [excalidraw/excalidraw-vscode#1]
Hi!

This extension is litreally a life saver, thanks **so** much!

Maybe, a suggestion, a way to toggle on autosave just for .excalidraw files? Like, when you draw a new component, resize something, etc, it auto saves.

Thanks!

**Comment by Milo123459** [comment]
^ Also, please bump the excalidraw package to 0.7.0

**Comment by pomdtr** [comment]
I think you can get this feature by using the `files.autoSave` setting. Mine is set to: `onFocusChange`.

**Comment by Milo123459** [comment]
Would this work for just 1 type of file though?

**Comment by pomdtr** [comment]
Sadly no :/ -> `This setting does not support per-language configuration.`

**Comment by Milo123459** [comment]
Sad :(

Do you know if it is possible to write autosave into the extension just for the .excalidraw files?

**Comment by pomdtr** [comment]
Yes it is pretty easy to achieve. I had it in a previous version, but it did feel like an hack (the dirty indicator was blinking on file change), so I removed it.

**Comment by Milo123459** [comment]
> Yes it is pretty easy to achieve. I had it in a previous version, but it did feel like an hack (the dirty indicator was blinking on file change), so I removed it.

Oh, I think maybe make it configurable, would be so helpful. Maybe also open an issue on microsoft/vscode asking about how you do it? (Removing the top left unsaved files count going from 1 to 0)

**Comment by pomdtr** [comment]
I think the issue can be resolved by directly writing to the file instead of creating a workspace edit.

**Comment by Milo123459** [comment]
> I think the issue can be resolved by directly writing to the file instead of creating a workspace edit.

Yes, that'd work!

**Comment by pomdtr** [comment]
fixed in 8110d4f3908bd9a29d8c7ae7de109b6f05150866
