### ISSUE TITLE
Support embedded scene in png

### ISSUE THREAD

**Issue by nyonson** [excalidraw/excalidraw-vscode#10]
I believe the workflow with the plugin currently requires having a separate excalidraw file per exported png. Would it be possible to take advantage of excalidraw's embedded schene in png feature?

**Comment by pomdtr** [comment]
Sadly this feature is not available in the npm package :/

**Comment by johan1252** [comment]
Looks like embedded scene support is included in latest version of the plugin (not yet in VsCode extensions marketplace).
The toggle `exportEmbedScene` should apply to both .svg and .png as per below:
https://github.com/excalidraw/excalidraw/blob/1c11df011a2f1eaf7f1164f475c94fc3ebe9f36b/src/data/index.ts#L80

**Comment by johan1252** [comment]
@pomdtr Do you know when a new version will be released in the VsCode marketplace?
I have been looking to use the embedded scene option for .svg export but VsCode marketplace version is still v1.2.0

**Comment by pomdtr** [comment]
Yeah I'm a bit lost in refactoring hell right now, I'll try to merge my changes this weekend 😅 

You're looking at the wrong file for the export function, the utility available in the API is https://github.com/excalidraw/excalidraw/blob/1c11df011a2f1eaf7f1164f475c94fc3ebe9f36b/src/packages/utils.ts#L51

**Comment by leighmcculloch** [comment]
:woah: If the vscode plugin had the capability to also open a png with an embedded excalidraw scene, and then save directly back to the png, that would make for an amazing workflow since all diagrams could live in git repos as PNGs only. 

This would bring the plugin in line with the draw.io vscode plugin that also supports editing and saving back directly to .drawio.png files.

**Comment by pomdtr** [comment]
This looks achievable with the latest version of the excalidraw library. However, I would need to implement a `customEditorProvider` inside VSCode, which looks harder to implement than the exisiting `customTextEditorProvider`
