### ISSUE TITLE
Missing 'Frame' feature

### ISSUE THREAD

**Issue by kevinjalbert** [excalidraw/excalidraw-vscode#102]
On the official version there is the 'Frame' tool, but in the VSCode version we are missing this.

![image](https://github.com/excalidraw/excalidraw-vscode/assets/574871/03a4ed2a-4190-47c5-b705-60da1c555579)

A new release of this extension hasn't happened since April 2023. Is this as simple as updating the excalidraw dependency and push a new release out? Or is there more to get this support here?

**Comment by pomdtr** [comment]
a new version of the extension has been released, adding support for this feature :)
