### ISSUE TITLE
excalidraw broken with vscode 1.82.2 - error loading webview

### ISSUE THREAD

**Issue by mkeller-gms** [excalidraw/excalidraw-vscode#103]
**Issue**
Within vscode, excalidraw tabs opens but do not show a drawing, after a few seconds a popup (right buttom) shows following message: "Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state."

I created a new file (empty file with .excalidraw extension), as before. But still the issue remains (so I assume documet is in valid state, I mean file is not corrupt)

**Versions**
vscode 1.82.2  (not working)
vscode 1.82.1 (working)
excalidraw 3.5.1

**Situation**
* Today, I upgraded to vscode 1.82.2 from some versions before. Couldn't figure out, if excalidraw extension had been upgraded. Might something had changed within vscode?
* After some weeks of testing I collected a lot of notes which are now no more accessible.
* Please drop a note, if you need any further information (or if you cannot reproduce this issue)
* [Edit1:] Just *downgraded* to 1.82.1 (https://update.code.visualstudio.com/1.82.1/win32-x64/stable) and *it is working again*, so something had changed between 1.82.2 and 1.82.1

**Comment by janfrederik** [comment]
Excalidraw 3.6.1 doesn't work with 1.83 either. The "runtime status" of the extension says "Not yet activated".

Version info:

![image](https://github.com/excalidraw/excalidraw-vscode/assets/18148910/e75494fa-f519-4f13-a84c-941864f657c5)

![image](https://github.com/excalidraw/excalidraw-vscode/assets/18148910/82196046-edc1-427e-a12a-17610547ec4f)

**Comment by janfrederik** [comment]
Oops, correction. After reloading VSCode, it works perfectly :-)

@mkeller-gms Maybe you should try again with the most recent versions of VSCode and the Excalidraw extension.

**Comment by pomdtr** [comment]
Maybe there is something sketchy going on here. Let's keep the issue open.

**Comment by mkeller-gms** [comment]
Retest: vscode 1.83.0  + Excalidraw 3.6.1 -- is working
Thank you for your followups.
