### ISSUE TITLE
Change the width of drawing pen in vscode

### ISSUE THREAD

**Issue by nguptaHQ** [excalidraw/excalidraw-vscode#104]
I am not able to reduce the stroke width. The 3 setting is not sufficient for me.

![image](https://github.com/excalidraw/excalidraw-vscode/assets/24511086/196cea2a-83da-412b-bcc5-2bf9920ed474)

I am trying to change using vscode setting, but it is not reflecting the changes. 

![image](https://github.com/excalidraw/excalidraw-vscode/assets/24511086/d4fe6bb2-1009-406a-b112-5b008ab265fa)

Please suggest me the correct way to reduce stroke width

**Comment by pomdtr** [comment]
Please post this issue in the excalidraw repository, this is outside of the extension scope.
