### ISSUE TITLE
Feature Request: Allow users to search local library

### ISSUE THREAD

**Issue by Wandergarten** [excalidraw/excalidraw-vscode#105]
Hi there! 
Excalidraw (within VS Code) is my Go-To drawing & sketching tool for various IT projects I'm working on. IMO, excalidraw has a wonderful, fresh and neat look that's great - esp. for the non-techie crowd - to comprehend.

I often use libraries and have imported quite some into my local stash. One thing I'm missing though is a search function - just like on the excalidraw library website. Am I missing something or would this be an _enhancement_? 

Thank you so much for you work!

**Comment by pomdtr** [comment]
thanks for the nice words!

the vscode extension is trying to mirror the website UI as close as possible, can you submit you feature request on the https://github.com/excalidraw/excalidraw repository ?

**Comment by Wandergarten** [comment]
Thanks for the hint! I found an open issue [#6802](https://github.com/excalidraw/excalidraw/issues/6802). 
I'm closing this issue then. Keep up the good work, excalidraw devs! 💪🖤

**Comment by Wandergarten** [comment]
closed
