### ISSUE TITLE
Rename frame doesnt work

### ISSUE THREAD

**Issue by jpillor-macquarie** [excalidraw/excalidraw-vscode#106]
Seems it was fixed here https://github.com/excalidraw/excalidraw/pull/7037

**Comment by pomdtr** [comment]
Thx! The fix will be merged once the excalidraw team release a new version of the npm package.

**Comment by Mat4m0** [comment]
Many thanks for this awesome plugin!

Since the npm package was already [updated to 0.17.0](https://www.npmjs.com/package/@excalidraw/excalidraw)
Is there any fix on the horizon?

**Comment by pomdtr** [comment]
thanks for notifying me!
