### ISSUE TITLE
Support for Images

### ISSUE THREAD

**Issue by Merglasch** [excalidraw/excalidraw-vscode#11]
First of all, thank you for this plugin. Being able to use Excalidraw from within vscode is an amazing thing :D

I'm guessing this is more a feature/update request. I've noticed there is no support for images in the plugin yet, but the webversion has them. This also means saved excalidraw files with images in them will load without images in vscode. This hinders me greatly as I use excalidraw frequently to make snapshots of coding work (in vscode,etc.) and annotate/color/marker the hell out of it. So, I'd love for this to be added/brought up to sync with the web version :)

**Comment by pomdtr** [comment]
Hey, thanks for the feedback!

I need to investigate if it is doable with the current state of the excalidraw API. I don't have much motivation and time to code outside of my working hours right now, but I really want to to update this extension as soon as I can.
