### ISSUE TITLE
Previously working file no longer opens.

### ISSUE THREAD

**Issue by p-stevenson** [excalidraw/excalidraw-vscode#15]
I can start a new drawing no problem. I can open the drawing in the online editor, but the
plugin just returns a blank screen. No idea what could be the issue here.

**Comment by p-stevenson** [comment]
I was able to restore the file by importing it into the online editor and then exporting it as an .svg which I then renamed to .excalidraw.

**Comment by pomdtr** [comment]
Sorry about that. I'm now using the native import / export from excalidraw, there might be some compatibility issues here.
Do you still have a version of the original file ? I would like to fix the issue for future users.

**Comment by p-stevenson** [comment]
No need to apologise, I'm very happy to have the plugin. It's so nice to be able to do everything inside vscode. 
File attached.
[original.txt](https://github.com/pomdtr/vscode-excalidraw-editor/files/8344670/original.txt)

**Comment by pomdtr** [comment]
Thanks for the kind words ! I found the issue, it should be corrected in 2.0.9 :)
