### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by cbyrd01** [excalidraw/excalidraw-vscode#18]
It appears excalidraw is under a MIT license (https://github.com/excalidraw/excalidraw/blob/master/LICENSE), however excalidraw-vscode does not specify a license. Adding a license will allow users to determine what their rights are with respect to the software, and allow them to ensure they are meeting the developer's wishes regarding appropriate use.

**Comment by pomdtr** [comment]
There is a LICENSE in the extension directory (vscode requires it at this location to build the extension): https://github.com/excalidraw/excalidraw-vscode/blob/master/extension/LICENSE

I don't know if it is necessary to also add it in the top level directory ?

**Comment by cbyrd01** [comment]
To be honest I didn't notice it in the extension directory (thanks for the comment) but I think others may not as well.

I do think adding it at the top level will make it more visible, and may work with systems that expect to see it there (for example, I think GitHub expects it at the top level to assign a license to the repository for searches, in the about page, etc.)

Thank you for your work on this fantastic project! I find it incredibly useful, and with integration to vscode it is even better!

**Comment by pomdtr** [comment]
Thanks ! I'll duplicate the file to the root directory.
