### ISSUE TITLE
Autozen mode

### ISSUE THREAD

**Issue by Milo123459** [excalidraw/excalidraw-vscode#2]
Maybe a feature that automatically enters zen mode for you?

**Comment by pomdtr** [comment]
Thank you for the suggestion, I will consider it for the next release :)

**Comment by pomdtr** [comment]
I think we could add a setting similar to the darkmode toggle with three options:
- on
- off
- auto (looks like the zenMode information is available in https://code.visualstudio.com/api/references/when-clause-contexts, I don't know if i can query with through vscode API)

**Comment by pomdtr** [comment]
Looks like it's not possible : https://stackoverflow.com/questions/59907805/is-it-possible-in-vsc-to-detect-if-zen-mode-is-enabled, https://github.com/microsoft/vscode/issues/89278

**Comment by pomdtr** [comment]
Then a defaultsToZenMode setting is the best solution available.

**Comment by Milo123459** [comment]
No, I meant as in just zen mode for the excalidraw gui so its just that, not vscode zen mode. That's what I meant. Not checking if zenmode is enabled in vscode

**Comment by pomdtr** [comment]
I am not interested in this feature anymore, as I want to have the smallest codebase possible to allow easy upgrades.
