### ISSUE TITLE
Contact the creator of the Excalidraw integration extension

### ISSUE THREAD

**Issue by pomdtr** [excalidraw/excalidraw-vscode#20]
Hi @brijeshb42 !

Following our conversation on https://github.com/brijeshb42/vscode-excalidraw/issues/16, would you be willing to unpublish your extension from the vscode marketplace ?

Since this extension is now integrated to the excalidraw ecosystem, we would like to avoid confusion for contributors and users by having a single excalidraw extension in the marketplace.

I did try to contact you on twitter but your dm are closed, so I hope a mention in this issue will reach you !

Have a great day.

**Comment by pomdtr** [comment]
Looks like the extension was unpublished. Thanks @brijeshb42 !

**Comment by dwelle** [comment]
Thanks @brijeshb42 ❤️!
