### ISSUE TITLE
Allow the user to set excalidraw theme to `light` or `dark`

### ISSUE THREAD

**Issue by pomdtr** [excalidraw/excalidraw-vscode#22]
The main issue to handle is a setting change while the document was in the background.

**Comment by ad1992** [comment]
@pomdtr its already present in the package, the host can use [theme](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md#theme) prop to set it.

**Comment by pomdtr** [comment]
@ad1992  yes, the issue is not related to the excalidraw package, it is specific to the extension.

Currently the user is able to control the theme from the extension using the `excalidraw.syncTheme` setting. However, I would like to provide an `excalidraw.theme` option instead, providing a dropdown with `auto`, `dark` or `light` options.

**Comment by mderazon** [comment]
@pomdtr any ETA on when this will be merged ?
It's a great addition. My VSC theme is dark, but I don't like Excalidraw dark mode and prefer the white one so it's nice to be able to override that.

**Comment by mderazon** [comment]
Sorry, my bad, I changed `excalidraw.syncTheme` but didn't realize that I had to close the document and reopen.
Now it's all good.

Thanks for this really useful extension!

**Comment by pomdtr** [comment]
This will be fixed in the next version of the extension (you can test it using the pre-release version).

Thanks for the nice words !
