### ISSUE TITLE
Copy and paste not working within text elements on MacOS

### ISSUE THREAD

**Issue by json2d** [excalidraw/excalidraw-vscode#41]
hey can't seem to copy text highlighted from within text elements, as well as paste from clipboard into text elements. might this be supported at some point?

os:
MacOS BigSur

versions:
2.0.16
2.1.12

**Comment by pomdtr** [comment]
It looks like an issue related to vscode desktop. I am able to reproduce this on macos, but not on the web version.

I'll create an issue in the vscode repository.

**Comment by pomdtr** [comment]
Seems linked with https://github.com/microsoft/vscode/issues/141080

As a workaround, right-click -> copy is working fine on macos
