### ISSUE TITLE
editor shortcuts bubble outside

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw-vscode#42]
For example, undo/redo shortcuts (ctrl-z/ctrl-y) also trigger vscode's undo/redo.

`Ctrl-x` to cut doesn't work at all for some reason, though this may be unrelated to this issue.

**Comment by pomdtr** [comment]
In what environment did the issue occurs ? I did not encounter the problem on vscode desktop

**Comment by pomdtr** [comment]
I think this is linked to the switch from a customtexteditor to a customeditor.
