### ISSUE TITLE
Configure the customized font in extension

### ISSUE THREAD

**Issue by Anddd7** [excalidraw/excalidraw-vscode#48]
Is there any easy way to replace default fonts? or add a new one by extension configuration. like https://github.com/zsviczian/obsidian-excalidraw-plugin?

(I'm willing to raise PR if you can provide some guidance 😄

**Comment by pomdtr** [comment]
Thanks for raising the issue in the upstream repository !

The vscode extension is just a wrapper around the npm package, so we should update the api before implementing the feature in the extension.

**Comment by pomdtr** [comment]
I did take a look at how @zviczian obsidian implemented it, but it looks like it breaks compatibility with excalidraw.com.

**Comment by Anddd7** [comment]
Thanks for reply.

Yes, is it possible to provide a fourth font which can be configured or overwritten via env, param or dropdown?

- via env, `CUSTOMIZED_FONT_NAME=xxxx, CUSTOMIZED_FONT_SRC=https://xxxx/xxx.ttf`
- param, `https://<excalidraw_host>?customized_font=xxxx`
- dropdown or input on left menu

**Comment by pomdtr** [comment]
The best thing without too much tweaking would be to allow the customization of the EXCALIDRAW_ASSET_PATH value: https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README_NEXT.md#installation

You should then be able to customize the font used for the Virgil, Helvetica and Cascadia fonts by hosting your own asset folder.

**Comment by Anddd7** [comment]
I see, i can repleace the font file and rebuild a customized plugin as well. 

Thanks for your sugguestion, I'll close this issue.
