### ISSUE TITLE
Auto-export on save

### ISSUE THREAD

**Issue by LeNouveau** [excalidraw/excalidraw-vscode#51]
Hi, 

Is it possible to always export my drawing on save ? 
Not everyone know how to use `.excalidraw` files and it is repetitive to export the file à each update. 

Some options would be : 
- Where ? (next to my source file, in my case)
- Which format ? (`.svg`, but it could also be `.png`)
- Filename ? (I would only change the extension)

Regards,

**Comment by pomdtr** [comment]
Did you try to us an `.excalidraw.svg` or `.excalidraw.png` file extension ? It allows to store both the schema and the image in the same file. You can see a demo in this tweet: https://twitter.com/excalidraw/status/1534585011361423360

**Comment by pomdtr** [comment]
I'm going to label this as **wontfix** since I feel like using a file with a `.excalidraw.png` extension is a better way to garanty that the schema and the image are in sync.

**Comment by LeNouveau** [comment]
Hi, 

You're right, I did know this feature but is works as I wished. 

Thank you !
