### ISSUE TITLE
Support for custom Excalidraw URLs

### ISSUE THREAD

**Issue by tudortimi** [excalidraw/excalidraw-vscode#57]
I'm using Excalidraw in a corporate environment, where we have an own installation. It would be cool if the extension would allow users to specify the Excalidraw URL.

**Comment by pomdtr** [comment]
What do you mean ? The extension does not communicate with the excalidraw server, everything is running locally.

**Comment by tudortimi** [comment]
Ah, okay. I had some issues running it where stuff didn't render and I assumed it was because it was trying to reach the server. I didn't consider that you can embed Excalidraw in an extension.
