### ISSUE TITLE
[Feature Request] Support vsc's display language (locale)

### ISSUE THREAD

**Issue by duskmoon314** [excalidraw/excalidraw-vscode#58]
VSCode provides a feature of [display language](https://code.visualstudio.com/docs/getstarted/locales). For example, we can use VSCode in mostly Chinese.

Maybe there is a method to get the using display language and pass it to excalidraw's `langCode`. Then we can use it in other languages automatically.

**Comment by pomdtr** [comment]
Thanks for mentioning it, I was not aware of it. I will take a look at it

**Comment by pomdtr** [comment]
Released in v3.3.0 :)
