### ISSUE TITLE
Missing hand draw font family on MacOS

### ISSUE THREAD

**Issue by stauvel** [excalidraw/excalidraw-vscode#60]
My sketches are beautiful in browser (right side), thx Excalidraw team, but under VSCode on MacOS(left side), I have hand draw font family replaced by Times like font. Same problem with drawio plugin.

<img width="981" alt="Capture d’écran 2022-09-02 à 15 35 57" src="https://user-images.githubusercontent.com/11860358/188157923-956168ae-461d-4c1e-a40f-8266c00f3d98.png">

Any idea how I can setup the hand draw font family on VSCode under MacOS ?

**Comment by stauvel** [comment]
I finally resolve it by myself : just save a first time a sketch made with a browser and then open it to download the fonts...

**Comment by pomdtr** [comment]
You should not need to do this 😅. Next time it happens, can you look at the network request tab in the developper tools ?

**Comment by LudoGH** [comment]
I have the same **'missing Virgil font**' problem on my Windows PC at work.
=> The network request tab of the developper tools shows **INTERNET_DISCONNECTED error**s trying to download the vendor and fonts from https://unpkg.com.
(this site may indeed be blacklisted by my workplace proxy).
One of the reasons I use excalidraw in vscode is to work offline.
=> Am I assuming this wrong? Is there a workaround for the fonts?
Apart from the font problem, it runs very well. Great tool :)

**Comment by pomdtr** [comment]
Thanks for reporting. Something might be wrong, it should use local fonts instead.

**Comment by Fraetor** [comment]
![image](https://user-images.githubusercontent.com/38766515/221995428-ec8f68cf-6e54-4ff5-a04f-bccb48f9dbff.png)

I've had this issue occur on Linux. It seems that the font is being blocked by CORS.

**Comment by LudoGH** [comment]
> Thanks for reporting. Something might be wrong, it should use local fonts instead.

Bonjour,
Any chances the Virgil font may be included in the plugin one day, and be used locally (instead of requiring it from unpkg.com) ?
Or suggest a workaround to use the plugin+font when working offline (or when unpkg is blocked)  ?
Again, very great tool, thx.

ps: could we remove 'MacOS' from the topic title, since it seems more related to use local Virgil Font (windows, linux, mac).

**Comment by pomdtr** [comment]
> Any chances the Virgil font may be included in the plugin one day, and be used locally (instead of requiring it from unpkg.com) ?

Workin on it!

**Comment by pomdtr** [comment]
Should be fixed in v3.5.0.

**Comment by LudoGH** [comment]
Hello,
The v3.5.0 fix works perfect for me :) vscode 1.77.3 with excalidraw-plugin 3.5.0 in Windows10.
Thank you so much Achille, this was the only thing that prevent me from using excalidraw at work.
Merci infiniment !
--
Ludovic
