### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by unional** [excalidraw/excalidraw-vscode#63]
When I install it and open a `test.excalidraw`, I got a blank page with no controls.
I do notice the `theme` icon on the top right so the extension is handling this file.

![image](https://user-images.githubusercontent.com/3254987/192122815-e2f16b4a-3203-4d48-99ab-45c21a22e867.png)

**Comment by pomdtr** [comment]
This extension is supposed to work on windows. Can you open the developer console and see if you spot any errors ?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/17577332/192145962-bc2dcaa6-7dd1-4453-bcbb-170afe2ed066.png">

**Comment by pomdtr** [comment]
Are you using vscodium by any chance ? There is an ongoing issue with openvsx: #56

**Comment by unional** [comment]
I'm using vscode.
Somehow it starts working now. Maybe after I reboot my computer. Don't know what went wrong. 🤷 

Thanks! 🌷

**Comment by sushruth** [comment]
EDIT: The issue somehow magically disappeared when I installed an older version manually by downloading  from [VSCode market place](https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) and then updating to new version. Something is definitely wrong here.

@unional I am experiencing this same issue in vscode-insiders right now - 

![image](https://user-images.githubusercontent.com/2114206/197068019-af4335b0-4d08-43ea-b330-97180836b30a.png)

This is what I see in the devtools. VSCode's service worker seems to be throwing a 401 on these URLs.

**Comment by henrikvilhelmberglund** [comment]
On Windows at least you need to restart VSCode for the extension to work.

**Comment by unional** [comment]
It is working for me since. If you encounter this issue, try @henrikvilhelmberglund suggestion. Close all VSCode instance and restart
