### ISSUE TITLE
Not able to add library

### ISSUE THREAD

**Issue by ganesshkumar** [excalidraw/excalidraw-vscode#8]
This is what I see when I click on the library button in VS Code

![image](https://user-images.githubusercontent.com/2135089/124411416-1b58ac00-dd6a-11eb-9015-c461c0bbafa2.png)

And this is what we see when we use the PWA

![image](https://user-images.githubusercontent.com/2135089/124411435-28759b00-dd6a-11eb-8925-dccb7a65ba42.png)

How do we import a library in VS Code. 

I am running on
* Windows
* VS Code 1.57.1

**Comment by pomdtr** [comment]
Hi. I did deactivate this feature because this was the import was not working using the vscode webview.
I think we could be able to allow library import by allowing the user to choose a file from the command palette.

**Comment by hughcameron** [comment]
Hi - I was wondering about this as well. I've been able to add groups to the library but I couldn't discover where the extension maintains these. I'd be interested in adding some of [these assets to the library](https://github.com/excalidraw/excalidraw-libraries).
