### ISSUE TITLE
Arrows are not clipped around the text

### ISSUE THREAD

**Issue by bouchaet** [excalidraw/excalidraw-vscode#80]
Hello,

It seems that the arrows are not clipped around its text when the PNG file is opened by a browser or even the Windows File Explorer. In VSCode, the clipping is visible and the text of the arrow appears normally. I haven't found a workaround for this, other than opening the "excalidraw.png" file from `excalidraw.com` website, and export to another PNG file. 

Thanks.

**Comment by rajguru7** [comment]
Hey,
I am facing the same problem while working with .excalidraw.png or .excalidraw.svg files.
In the first export to .excalidraw.png or .excalidraw.svg file the clipping is rendered properly. 
But once the same file is edited and saved  using vscode, the arrows lose the clipping around its text.

**Initial export** `sample.excalidraw.svg`
![sample excalidraw](https://user-images.githubusercontent.com/39670286/224022541-2ba207ea-f2c6-4ad1-852a-a27128387b8c.svg)

**Same file edited and saved** `sample.excalidraw.svg`
![sample excalidraw](https://user-images.githubusercontent.com/39670286/224023101-9e540d59-4434-4e69-9af7-e7bb03cb0b23.svg)

**Comment by pomdtr** [comment]
Yep I'm able to reproduce. It's probably an upstream bug, I will send an issue to the Excalidraw team

**Comment by pomdtr** [comment]
Should be fixed in v3.4.2. Thanks to @dwelle and @ad1992 for fixing the issue in the npm package <3
