### ISSUE TITLE
Support Latex 

### ISSUE THREAD

**Issue by julien-blanchon** [excalidraw/excalidraw-vscode#84]
This PR (https://github.com/excalidraw/excalidraw/pull/6037) introduce a Math mode in Excalidraw to integrate with Latex.

A live demo could be try here: https://math.preview.excalidraw.com/

How can I use the danieljgeiger-mathjax branch to get Latex inside VS Code ?

**Comment by pomdtr** [comment]
As stated in the README.md

> This extension only goal is to integrate Excalidraw to the Visual Studio Code ecosystem. Users should be able to use both the website and the extension with a minimal amount of friction. As such, we will not accept any contribution that significantly modify the user experience compared to the Excalidraw website.

So the extension won't support latex until support for it is added in excalidraw.com
