### ISSUE TITLE
[VScodium] Files not loading with latest update (~> 1.78)

### ISSUE THREAD

**Issue by alexis-renard** [excalidraw/excalidraw-vscode#88]
Hello,

Just want to raise a little problem with the latest update of **vscodium**, the .excalidraw files would just not load, making them all unusable.

OS : Windows 10
Arch : x64

Extension not working with : https://github.com/VSCodium/vscodium/releases/tag/1.78.1.23130

Fixed downgrading to : https://github.com/VSCodium/vscodium/releases/tag/1.77.3.23102

I unfortunately do not have much time to investigate on that, but wanted at least to raise the issue. Cheers !

**Comment by pomdtr** [comment]
Just tested on the latest vscodium release, it seems to work just fine.
