### ISSUE TITLE
Bring dark mode

### ISSUE THREAD

**Issue by ThomasAqtl** [excalidraw/excalidraw-vscode#9]
Since dark mode is now available on web app, it would a nice feature in this extension as well :)

**Comment by pomdtr** [comment]
I think this feature is already implemented. Try to change the excalidraw theme using the `Excalidraw: Color Theme` command! You can select light, dark or auto theme (auto matches the current vscode theme).

**Comment by rxliuli** [comment]
Sorry, I didn't notice this command, but it does work well
