### ISSUE TITLE
False file change detection in vscode for .excalidraw files

### ISSUE THREAD

**Issue by ali80** [excalidraw/excalidraw-vscode#96]
Hello,

I'm encountering an issue where Visual Studio Code (VSCode) incorrectly detects changes in .excalidraw files upon opening them, even when no modifications have been made. Here are the details:

Operating System: macOS
VSCode Version: 1.79.2
Excalidraw Extension Version: v3.5.1
## Steps to Reproduce:

Open a .excalidraw file in VSCode.
Do not make any changes to the file.
Notice that VSCode prompts a notification indicating that the file has been modified.
## Expected Behavior:
When opening an untouched .excalidraw file, VSCode should not display any false notifications indicating file modifications. or maybe excalidraw extension should not change the file on its own unnecessarily

**Comment by peterk62** [comment]
Same problem

**Comment by meeas** [comment]
I also wish this behavior was changed.  

I suspect it has more to do with the Excalidraw npm package than the vscode package, but this does cause headaches when using excalidraw in git repos.

**Comment by meeas** [comment]
This is a repeat of #94

**Comment by pomdtr** [comment]
as @meeas said, this is already tracked
