### ISSUE TITLE
Support for Obsidian's .excalidraw.md

### ISSUE THREAD

**Issue by V4G4X** [excalidraw/excalidraw-vscode#98]
[Feature Request] 
The way Excalidraw support embedding the diagram logic in `.png` and `.svg` files.  
It would be convenient to have `.excalidraw.md` as well, because this is the file that Obsidian's Excalidraw Plugin uses.  

It would be nice to have diagrams interchangeable between the two apps.

Sample `excalidraw.md` (Empty Diagram):  
> \---
> excalidraw-plugin: parsed
> tags: [excalidraw]
> \---
> ==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠==
> %%
> # Drawing
> \```json
>  {"type":"excalidraw","version":2,"source":"https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/1.9.12","elements":[],"appState":{"gridSize":null,"viewBackgroundColor":"#ffffff"}}
> \```
> %%

**Comment by pomdtr** [comment]
Hi! The excalidraw.md format is not officially supported by excalidraw, so it is out of scope for this extension:

> This extension only goal is to integrate Excalidraw to the Visual Studio Code ecosystem. Users should be able to use both the website and the extension with a minimal amount of friction. As such, we will not accept any contribution that significantly modify the user experience compared to the Excalidraw website.
