### ISSUE TITLE
Can't flip group or selection of multiple objects

### ISSUE THREAD

**Issue by peterk62** [excalidraw/excalidraw-vscode#99]
In the web version of Excalidraw I can flip groups and selections of multiple objects, but in the VSCode extension I seem to be only able to flip individual objects. If I create a test file, create a few lines etc. and group them, I can flip the group in the web version, but opening the same file in the extension does not allow this. Any thoughts?
Thanks

**Comment by pomdtr** [comment]
This is fixed in the newly released version
